#!/usr/bin/env bash
# theme.sh — derive the widget palette from the active Omarchy theme.
#
# Omarchy symlinks the current theme at ~/.config/omarchy/current/theme and
# every theme ships an alacritty.toml, which is the one colour file that is
# both always present and trivially parseable. Anything missing falls back to
# Tokyo Night, so this never hard-fails.
set -uo pipefail

CL_OMARCHY_THEME="${CL_OMARCHY_THEME:-$HOME/.config/omarchy/current/theme}"

cl_theme_main() {
  cl_dirs
  cl_load_config
  mkdir -p "$CL_EWW_DIR"

  local src="$CL_OMARCHY_THEME/alacritty.toml"
  local out="$CL_EWW_DIR/theme.scss"

  # Tokyo Night — the Omarchy default, and our fallback.
  local bg="#16161e" fg="#c0caf5" black="#15161e" red="#f7768e" green="#9ece6a"
  local yellow="#e0af68" blue="#7aa2f7" magenta="#bb9af7" cyan="#7dcfff" white="#a9b1d6"
  local source="built-in Tokyo Night"

  if [[ -f $src ]]; then
    local parsed; parsed="$(_cl_parse_alacritty "$src")"
    if [[ -n $parsed ]]; then
      local k v
      while IFS='=' read -r k v; do
        [[ -z $k || -z $v ]] && continue
        case "$k" in
          background) bg="$v" ;;   foreground) fg="$v" ;;
          black) black="$v" ;;     red) red="$v" ;;
          green) green="$v" ;;     yellow) yellow="$v" ;;
          blue) blue="$v" ;;       magenta) magenta="$v" ;;
          cyan) cyan="$v" ;;       white) white="$v" ;;
        esac
      done <<< "$parsed"
      source="$(cl_shorten "$(readlink -f "$CL_OMARCHY_THEME" 2>/dev/null || printf '%s' "$CL_OMARCHY_THEME")")"
    fi
  fi

  # Omarchy marks light themes with a light.mode file next to the colours.
  local is_light="false"
  [[ -f $CL_OMARCHY_THEME/light.mode ]] && is_light="true"

  cat > "$out" <<EOF
// Generated by \`claude-launcher theme\` — do not edit by hand.
// Source: $source

\$is-light: $is_light;

\$bg:      $bg;
\$fg:      $fg;
\$black:   $black;
\$red:     $red;
\$green:   $green;
\$yellow:  $yellow;
\$blue:    $blue;
\$magenta: $magenta;
\$cyan:    $cyan;
\$white:   $white;
EOF

  printf 'palette written to %s (source: %s)\n' "$(cl_shorten "$out")" "$source"
}

# Emits "key=#rrggbb" lines for [colors.primary] and [colors.normal].
_cl_parse_alacritty() {
  awk '
    /^[[:space:]]*\[/ {
      section = $0
      gsub(/[][[:space:]"]/, "", section)
      next
    }
    section == "colors.primary" || section == "colors.normal" {
      line = $0
      if (line !~ /=/) next
      key = substr(line, 1, index(line, "=") - 1)
      gsub(/[[:space:]]/, "", key)
      rest = substr(line, index(line, "=") + 1)

      # TOML allows both quote styles; normalise to double so one branch
      # handles each. (sprintf avoids a literal quote in the awk source.)
      gsub(sprintf("%c", 39), "\"", rest)

      # Take the quoted value verbatim — stripping "comments" first would eat
      # the # of a "#rrggbb" colour. Only unquoted values can carry a comment.
      if (match(rest, /"[^"]*"/)) {
        val = substr(rest, RSTART + 1, RLENGTH - 2)
      } else {
        sub(/#.*$/, "", rest)
        val = rest
      }
      gsub(/[[:space:]]/, "", val)

      if (val ~ /^0[xX]/) val = substr(val, 3)
      sub(/^#/, "", val)
      if (val ~ /^[0-9a-fA-F]{6}$/) print key "=#" tolower(val)
    }
  ' "$1" 2>/dev/null
}
